if(NOT DEFINED FIDGET_FONT_EMBED_TOOL
   OR NOT DEFINED FIDGET_FONT_INPUT_DIRECTORY
   OR NOT DEFINED FIDGET_FONT_INPUT_NAME
   OR NOT DEFINED FIDGET_FONT_SYMBOL
   OR NOT DEFINED FIDGET_FONT_OUTPUT)
    message(FATAL_ERROR "The embedded-font generator is missing an input.")
endif()

execute_process(
    COMMAND
        "${FIDGET_FONT_EMBED_TOOL}"
        -u8
        "${FIDGET_FONT_INPUT_NAME}"
        "${FIDGET_FONT_SYMBOL}"
    WORKING_DIRECTORY "${FIDGET_FONT_INPUT_DIRECTORY}"
    OUTPUT_FILE "${FIDGET_FONT_OUTPUT}"
    ERROR_VARIABLE FIDGET_FONT_EMBED_ERROR
    RESULT_VARIABLE FIDGET_FONT_EMBED_RESULT
)

if(NOT FIDGET_FONT_EMBED_RESULT EQUAL 0)
    file(REMOVE "${FIDGET_FONT_OUTPUT}")
    message(FATAL_ERROR
        "Could not embed ${FIDGET_FONT_INPUT_NAME}: "
        "${FIDGET_FONT_EMBED_ERROR}")
endif()
